### PR TITLE
Removed usages of deprecated methods

### PR DESCRIPTION
**Pull request by LukBukkit**
I replaced the old methods WikiPage::dotEdit() and WikiPage::getText() with new methods

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Thanks for the PR!

Was this code available in MediaWiki 1.23? If not, the PR is premature. Do note how the usage of the deprecated method only happens when the new approach is not available.

**Comment by LukBukkit** [comment]
Yes, it should work in 1.23, but i'll try it out.

Jeroen De Dauw <notifications@github.com> schrieb am Sa., 17. Dez. 2016,
00:04:

**Comment by reedy** [comment]
@JeroenDeDauw It was in 1.21 :)

https://github.com/wikimedia/mediawiki/blob/master/includes/content/WikitextContent.php#L20

https://github.com/wikimedia/mediawiki/blob/master/includes/page/WikiPage.php#L1553
https://github.com/wikimedia/mediawiki/blob/master/includes/page/WikiPage.php#L1617

**Comment by JeroenDeDauw** [comment]
Thanks @LukBukkit and @reedy

**Comment by kghbln** [comment]
@JeroenDeDauw rel 1.4.1?

**Comment by JeroenDeDauw** [comment]
No need. This is minor code clean up that does not affect the users

**Comment by kghbln** [comment]
> No need. This is minor code clean up that does not affect the users

Ah, and I thought the the previous code was breaking for MW 1.29+. No worries.

**Pull request merged**
