### PR TITLE
adds HTML element option "none"

### PR DESCRIPTION
**Pull request by emanspeaks**
This allows raw wikitext to be returned instead of wrapping in HTML tags.

I have no idea if my test will even work, but submitting anyway and will just see how it goes.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Thanks a lot @emanspeaks!

**Comment by JeroenDeDauw** [comment]
You will also update USAGE.md and RELEASE-NOTESmd?

**Comment by emanspeaks** [comment]
Ah, forgot release notes, but USAGE is updated.

**Comment by JeroenDeDauw** [comment]
> USAGE is updated

Oh wow, I was being rather blind there

**Pull request merged**
