### PR TITLE
New parameter "addlevel"

### PR DESCRIPTION
**Pull request by emanspeaks**
This is actually independent of issue #3. This allows the user to add extra bullets to the list so you can use this list inside of another list; it does not modify the list itself. Works best if used with the "element=none" option so that this can nest inside of another list in wikitext.

So instead of

    * A 
    ** 1  
    ** 2
    * B

You can use "addlevel=1" to get

    ** A
    *** 1
    *** 2
    ** B

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Thanks once again!

**Comment by JeroenDeDauw** [comment]
FYI: it's better to not have a chain of commits with a few failing ones in there. That messes up things such as git-bisect. Squashing the commits together is preferred

**Comment by JeroenDeDauw** [comment]
I've added another test in #18 out of paranoia

**Comment by emanspeaks** [comment]
Thanks for the tips.  I'm fairly new to Git and GitHub, so I appreciate your patience as I learn how to use this the hard way.  I'm just happy to actually be contributing to stuff finally!

**Pull request merged**
